export const userList = [
  {
    id: 1,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "t",
  },
  {
    id: 2,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "t",
  },
  {
    id: 3,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "t",
  },
  {
    id: 4,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 5,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 6,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 7,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 8,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 9,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 10,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 11,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 12,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 13,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 14,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 15,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 16,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 17,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 18,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 19,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 20,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
  {
    id: 21,
    firstName: "test",
    lastName: "1",
    email: "test@test.com",
    appVersion: "1.0.0",
    createdAt: "2023 06 17 08:54:09",
    isActive: "f",
  },
];

export const fakeJobs = [
  {
    id: 192,
    title: "Seeking a Full-stack developer ",
    description: "I am seeking in upwrok..",
    price: 1111,
    expectedDeliveryTime:
      "Thu Jul 20 2023 17:23:44 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 11 17:25:20",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 10,
      name: "Translation",
      isActive: true,
    },
    subCategory: [
      {
        id: 41,
        name: "Physical Sciences",
        isActive: true,
      },
    ],
    user: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
      userprofile: {
        id: 21,
        aboutMe:
          "As a full-stack developer, I have an experience with over 3 years in web development. If you are interested in me, don't hesitate to contact me. I look forward to hearing from you.",
        profession: "Full Stack developer",
        rate: "0",
        country: "Malaysia",
        city: "Bangi",
        birth: "2000-10-17T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 1,
        name: "React",
      },
    ],
    favor: {
      id: 99,
      type: "job",
      targetId: 192,
    },
  },
  {
    id: 193,
    title: "Implement adding new reports to dashboard for CodeIgniter SaaS app",
    description:
      "To enhance the dashboard of our CodeIgniter school application, we need to add new reports sourced from the database. We already have existing reports that can serve as a reference for incorporating these new reports. The display logic should remain consistent, showing the reports specifically for admin users. Additionally, I have the PHP and MySQL codes readily available for seamless implementation, eliminating the need for brainstorming on your part.\n\nThe ideal candidate should have excellent skills in CodeIgniter, CSS, JavaScript, Highcharts, MySQL, and PHP.\n\nPlease read the attached file first and be sure you can deliver the tasks before you apply.\n\nIf you are interested in this project, please submit a detailed proposal describing your experience and how you can help with this project. Please also include links to past completed projects that are relevant to this job. We look forward to hearing from you soon.",
    price: 1234,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:34:03 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:36:36",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 8,
      name: "Legal",
      isActive: true,
    },
    subCategory: [
      {
        id: 74,
        name: "Editing & Proofreading Services",
        isActive: true,
      },
    ],
    user: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
      userprofile: {
        id: 23,
        aboutMe: "I am a developer",
        profession: "Web developer",
        rate: "0",
        country: "Bahrain",
        city: "Sanad",
        birth: "1949-12-31T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 43,
        name: "Chinese",
      },
      {
        id: 44,
        name: "German",
      },
      {
        id: 53,
        name: "Postgre",
      },
    ],
    favor: {
      id: 108,
      type: "job",
      targetId: 193,
    },
  },
  {
    id: 194,
    title: "Adding GPT API translation to Shopify website",
    description:
      "We have Shopify e-commerce store, currently we have translation apps that is helping to translate all the content in the website, but we want GPT API that can be integrated to our website and also this api should save all the translated text data in shopify server.\n\nIf you have related experience, please submit your proposal with brief plan, links to previous projects that have similar requirements.\n\nPlease consider that we have fixed budget.",
    price: 1111,
    expectedDeliveryTime:
      "Wed Jul 19 2023 09:37:05 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:37:36",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 4,
      name: "Data Science & Analytics",
      isActive: true,
    },
    subCategory: [
      {
        id: 18,
        name: "Data Analysis & Testing",
        isActive: true,
      },
    ],
    user: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
      userprofile: {
        id: 23,
        aboutMe: "I am a developer",
        profession: "Web developer",
        rate: "0",
        country: "Bahrain",
        city: "Sanad",
        birth: "1949-12-31T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 41,
        name: "Nigerian",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 44,
        name: "German",
      },
      {
        id: 45,
        name: "Github",
      },
      {
        id: 53,
        name: "Postgre",
      },
    ],
    favor: null,
  },
  {
    id: 195,
    title: "Copy swatches images to variations with mysql query",
    description:
      "My data operator missed to upload the images in variations and he uploaded in swatches. Is it possible to copy the images from swatches to variations with mysql query. Only developers who has deep knowledge of wordpress db structure can do it. Do not waste time to search how to do it. I need expert who can do this task in 1 hour.",
    price: 1234,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:37:41 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:38:53",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 9,
      name: "Sales & Marketing",
      isActive: true,
    },
    subCategory: [
      {
        id: 23,
        name: "Art & Illustration",
        isActive: true,
      },
    ],
    user: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
      userprofile: {
        id: 23,
        aboutMe: "I am a developer",
        profession: "Web developer",
        rate: "0",
        country: "Bahrain",
        city: "Sanad",
        birth: "1949-12-31T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 41,
        name: "Nigerian",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 1,
        name: "React",
      },
    ],
    favor: null,
  },
  {
    id: 196,
    title: "WordPress Dashboard to Manage Candidates",
    description:
      "We are seeking a skilled and experienced freelance Dashboard Developer to assist us in building a comprehensive and user-friendly dashboard for our WordPress website. The primary purpose of the dashboard will be to streamline the management of candidates applying for job positions within our company and to handle the submission and organization of their documents.\n\nResponsibilities:\n- Collaborate with our team to understand the requirements and design specifications for the dashboard.\n- Develop a visually appealing and intuitive dashboard using WordPress that allows efficient management of candidate applications and associated documents.\n- Implement user-friendly features and functionalities to facilitate seamless navigation and interaction within the dashboard.\n- Integrate necessary plugins and tools to enable document submission, storage, and retrieval within the dashboard.\n- Ensure the dashboard is responsive and compatible with various devices and browsers.\n- Implement appropriate security measures to protect sensitive candidate data and documents.\n- Create a separate admin dashboard to provide access and control to the administrators, allowing them to view and manage all candidate documents and details.\n\nRequirements:\n- Proven experience in developing WordPress websites and custom dashboards.\n- Strong proficiency in front-end development technologies such as HTML, CSS, JavaScript, and jQuery.\n- Extensive knowledge of WordPress CMS, themes, and plugins.\n- Familiarity with database management and integration within WordPress.\n- Experience in designing and implementing user-friendly interfaces and navigation.\n- Solid understanding of document management systems and practices.\n- Excellent problem-solving skills and attention to detail.\n- Ability to work independently and meet project deadlines.\n- Strong communication and collaboration skills.\n\nAdditional Information:\n- This is a remote freelance position.\n- The project timeline and compensation will be discussed during the interview process.\n\nReference Dashboard - ableteams.com\nThey provide the exact dashboard that I need.\nTry Logging in - app.ableteams.com/profile/#/LSI/hq/login\n\nshivammehta85@gmail.com\n123456789Asd\n\n\nIf you are a talented Dashboard Developer with expertise in WordPress and a passion for creating streamlined solutions, we would love to hear from you. Please submit your resume, portfolio, and any relevant examples of your previous work. We appreciate all applications, but only selected candidates will be contacted for further consideration.",
    price: 1144,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:38:58 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:39:49",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 4,
      name: "Data Science & Analytics",
      isActive: true,
    },
    subCategory: [
      {
        id: 17,
        name: "AI & Machine Learning",
        isActive: true,
      },
    ],
    user: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
      userprofile: {
        id: 23,
        aboutMe: "I am a developer",
        profession: "Web developer",
        rate: "0",
        country: "Bahrain",
        city: "Sanad",
        birth: "1949-12-31T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 41,
        name: "Nigerian",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 43,
        name: "Chinese",
      },
      {
        id: 44,
        name: "German",
      },
    ],
    favor: null,
  },
  {
    id: 197,
    title:
      "Looking For Experienced Full Stack Developer [Laravel,Vue.js,PHP] - Full Time Job",
    description:
      "Hi everyone,\n\nWe're looking to add a Fullstack Developer to our team that is an expert at working with Laravel, PHP , Vue.js\n\nYou must be disciplined to work and strive in our team, fast executions and eager to succeed, looking for a serious developer who wants to build a future with us. (Years ahead).\n\nThis job is for a fulltime monthly salary, you work fulltime with our team.\n\n*Only individual freelancers, no agencies please.\n*Don't apply if you don't meet our job criteria.\n*In your application, please send some samples of some recent related work/projects.\n\n\nThanks.",
    price: 134,
    expectedDeliveryTime:
      "Wed Jul 19 2023 09:40:29 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:41:11",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 4,
      name: "Data Science & Analytics",
      isActive: true,
    },
    subCategory: [
      {
        id: 18,
        name: "Data Analysis & Testing",
        isActive: true,
      },
    ],
    user: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
      userprofile: {
        id: 23,
        aboutMe: "I am a developer",
        profession: "Web developer",
        rate: "0",
        country: "Bahrain",
        city: "Sanad",
        birth: "1949-12-31T21:00:00.000Z",
        experience: [],
        portfolio: [],
        socialMediaLinks: {},
        createdAt: "2023-07-10:+0300",
        updatedAt: null,
      },
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 41,
        name: "Nigerian",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 43,
        name: "Chinese",
      },
      {
        id: 44,
        name: "German",
      },
      {
        id: 45,
        name: "Github",
      },
    ],
    favor: null,
  },
  {
    id: 198,
    title:
      "Wrong number of replies is displayed when a reply is flagged as offensive #20102 - Expensify",
    description:
      "Expensify is a team of generalists developing today's leading expense management tool. Maintaining our reputation as an innovative leader in the world of finance requires an incredibly reliable and secure system for processing financial transactions. Accordingly, we primarily leverage time-tested languages, but we're looking to unify our front-end across platforms. For this, we're leveraging React Native and are looking toward the community on Upwork to help solve a variety of problems, both big and small, related to this migration.\n\nPlease see the GitHub issue for full details: github.com/Expensify/App/issues/20102\n\nYour Proposal:\n\n- You *must* post a proposal for how you will fix this issue in the GitHub issue linked above.\n- Your proposal should include a technical explanation of the changes you will make.\n- Your proposal will be reviewed.\n- If your proposal is accepted, you should post the proposal in Upwork and you will be hired for the job.\n\nHow to submit the code:\n\nTo submit the code, we'll invite you to our GitHub repository, where you'll create a fork of our codebase. You'll create a branch on that fork, and when your code is ready for review, you'll create a pull request in our repository to merge your fix into our codebase. Our engineers will review the code, and approve and merge when the fix meets our requirements.\n\nPlease review our Contributor Guidelines before submitting a proposal -  https://github.com/Expensify/App/blob/main/CONTRIBUTING.md",
    price: 333,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:42:06 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:43:06",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 9,
      name: "Sales & Marketing",
      isActive: true,
    },
    subCategory: [
      {
        id: 26,
        name: "Graphic, Editorial & Presentation Design",
        isActive: true,
      },
    ],
    user: {
      id: 5037,
      firstName: "test1",
      lastName: "test1",
      email: "test@test1.com",
      password: "$2b$10$ZeDdkFruy.kQrps.2i7iqOLvXLpQO9XtsR.FXSFHAtnjkaDziyDPC",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: null,
      userprofile: null,
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 53,
        name: "Postgre",
      },
      {
        id: 56,
        name: "Firebase",
      },
      {
        id: 1,
        name: "React",
      },
      {
        id: 16,
        name: "Azure",
      },
      {
        id: 24,
        name: "Wordpress",
      },
      {
        id: 25,
        name: "Wordpress theme",
      },
      {
        id: 26,
        name: "Worepress Plugin",
      },
    ],
    favor: {
      id: 101,
      type: "job",
      targetId: 198,
    },
  },
  {
    id: 199,
    title: "Shopify custom templates with cart integration upgrades",
    description:
      "- Custom Product templates, with different add on selection options based on variant selection.\n\n- Redesign (Sorting, graphics addition to Collection pages)\n\n- Template building for custom pages and blog\n\n- Additional minor theme enhancements changes (Currently using Taste)\n\n- Consultation on adding on a small category of rental products (future project)",
    price: 555,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:43:10 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:44:44",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 9,
      name: "Sales & Marketing",
      isActive: true,
    },
    subCategory: [
      {
        id: 26,
        name: "Graphic, Editorial & Presentation Design",
        isActive: true,
      },
    ],
    user: {
      id: 5037,
      firstName: "test1",
      lastName: "test1",
      email: "test@test1.com",
      password: "$2b$10$ZeDdkFruy.kQrps.2i7iqOLvXLpQO9XtsR.FXSFHAtnjkaDziyDPC",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: null,
      userprofile: null,
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 40,
        name: "English",
      },
      {
        id: 41,
        name: "Nigerian",
      },
      {
        id: 42,
        name: "Japanese",
      },
      {
        id: 43,
        name: "Chinese",
      },
      {
        id: 44,
        name: "German",
      },
      {
        id: 45,
        name: "Github",
      },
      {
        id: 48,
        name: "Next.js",
      },
    ],
    favor: {
      id: 102,
      type: "job",
      targetId: 199,
    },
  },
  {
    id: 200,
    title: "Shopify Website Development",
    description:
      "We are looking for an experienced Shopify development team to carry out an initial project and then work together on an ongoing basis as projects arise.\n\nAbout us:\nWe are an ecommerce business based in Australia.\nWe have two websites - thebalconygarden.com.au and slugg.com.au which are both built on Shopify.\n\nOur websites use the following 3rd party integrations:\nHubspot (TBG)\nKlaviyo (Slugg)\nRebuy (TBG, Slugg once the initial project has been completed)\nElevar (TBG & Slugg)\nDear/Cin7 Core (TBG)\nQuantcast (TBG & Slugg)\nClarity (TBG & Slugg)\nGA4 (TBG & Slugg)\nLOOX (TBG & Slugg)\nReplo (TBG & Slugg)\nQuickbooks (TBG & Slugg)\nOptimonk (TBG)\nTriple Whale (TBG & Slugg)\nGTM (TBG & Slugg)\n\nThe first project we need to be completed is updating the Slugg.com.au website which is currently built on the Shopify theme - Shapes. We had some designs created for the Home page, product page and collections page which can be viewed here - https://www.figma.com/proto/lHRmN1o61kRELyugpiYa29/Slugg-%2F%2F-Oddit-Premium?page-id=2%3A137&node-id=1586-3&starting-point-node-id=1586%3A3&show-proto-sidebar=1.\n\nWe need every page rebuilt and will supply the designs via Figma files once complete. We require the site to be built in sections so we can reorder sections or make minor changes to copy and imagery ourselves.\n\nIf you are interested, please let me know if you require more information before you submit a fixed price. I'm happy to provide you with Shopify collaborator access so you can look around.\n\nPlease let me know if you have any more questions.\n\nThanks,\n\nJosh Harrison\n",
    price: 555,
    expectedDeliveryTime:
      "Wed Aug 09 2023 09:44:50 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:45:49",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 2,
      name: "Admin Support",
      isActive: true,
    },
    subCategory: [
      {
        id: 11,
        name: "Project Management",
        isActive: true,
      },
    ],
    user: {
      id: 5037,
      firstName: "test1",
      lastName: "test1",
      email: "test@test1.com",
      password: "$2b$10$ZeDdkFruy.kQrps.2i7iqOLvXLpQO9XtsR.FXSFHAtnjkaDziyDPC",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: null,
      userprofile: null,
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 40,
        name: "English",
      },
      {
        id: 43,
        name: "Chinese",
      },
      {
        id: 45,
        name: "Github",
      },
      {
        id: 2,
        name: "HTML",
      },
      {
        id: 23,
        name: "PHP",
      },
      {
        id: 25,
        name: "Wordpress theme",
      },
      {
        id: 27,
        name: "Python",
      },
    ],
    favor: {
      id: 103,
      type: "job",
      targetId: 200,
    },
  },
  {
    id: 201,
    title:
      "Wordpress - Dev. a Video Greeting Plugin for Flower Delivery Website",
    description:
      "We are seeking a skilled and experienced freelancer to code a custom video greeting WordPress plugin. The plugin should enable users to create and embed personalized video greetings seamlessly into the ordering process.\n\nKey qualifications include proven experience in coding WordPress plugins and a strong command of PHP, HTML, CSS, and JavaScript. The ideal candidate should be proficient in plugin development, possess excellent problem-solving skills, and have a track record of delivering high-quality solutions.",
    price: 777,
    expectedDeliveryTime:
      "Wed Jul 26 2023 09:45:55 GMT+0300 (Moscow Standard Time)",
    fileLocations: null,
    status: "1",
    createdAt: "2023 07 12 09:48:20",
    updatedAt: null,
    hiredAt: null,
    completedAt: null,
    completedUser: null,
    category: {
      id: 10,
      name: "Translation",
      isActive: true,
    },
    subCategory: [
      {
        id: 37,
        name: "Contract Manufacturing",
        isActive: true,
      },
    ],
    user: {
      id: 5037,
      firstName: "test1",
      lastName: "test1",
      email: "test@test1.com",
      password: "$2b$10$ZeDdkFruy.kQrps.2i7iqOLvXLpQO9XtsR.FXSFHAtnjkaDziyDPC",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: null,
      userprofile: null,
    },
    jobLevel: null,
    jobType: null,
    skill: [
      {
        id: 39,
        name: "Marketing",
      },
      {
        id: 55,
        name: "Full stack development",
      },
      {
        id: 35,
        name: "Sketch",
      },
    ],
    favor: {
      id: 104,
      type: "job",
      targetId: 201,
    },
  },
];

export const fakeGigs = [
  {
    id: 18,
    title: "Web designer",
    description: "I am a web designer with over 3 years of experience.",
    price: "300.00",
    fileLocations: [],
    status: "0",
    createdAt: "2023 07 11",
    updatedAt: "2023-07-11T14:10:14.327Z",
    isPublished: null,
    category: {
      id: 5,
      name: "Design & Creative",
      isActive: true,
    },
    subCategory: [
      {
        id: 54,
        name: "Digital Marketing",
        isActive: true,
      },
    ],
    user: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
    skill: [
      {
        id: 48,
        name: "Next.js",
      },
      {
        id: 1,
        name: "React",
      },
    ],
  },
];

export const fakeMessageList = [
  {
    id: 60,
    content: "hello",
    senderId: 5032,
    receiverId: 5036,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 04:54:55",
    stt: 1,
    receiver: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
    sender: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
  },
  {
    id: 61,
    content: "hello",
    senderId: 5036,
    receiverId: 5032,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 04:55:43",
    stt: 1,
    receiver: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
    sender: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
  },
  {
    id: 62,
    content: "are you ready?",
    senderId: 5032,
    receiverId: 5036,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 04:55:59",
    stt: 1,
    receiver: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
    sender: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
  },
  {
    id: 63,
    content: "hello",
    senderId: 5036,
    receiverId: 5032,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 05:06:42",
    stt: 1,
    receiver: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
    sender: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
  },
  {
    id: 64,
    content: "are you there?",
    senderId: 5036,
    receiverId: 5032,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 05:06:56",
    stt: 1,
    receiver: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
    sender: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
  },
  {
    id: 65,
    content: "Sure, I am here.",
    senderId: 5032,
    receiverId: 5036,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 07:12:48",
    stt: 1,
    receiver: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
    sender: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
  },
  {
    id: 66,
    content: "What's the matter, dear?",
    senderId: 5032,
    receiverId: 5036,
    roomId: "50325036192",
    type: "",
    createdAt: "2023 07 12 07:13:00",
    stt: 1,
    receiver: {
      id: 5036,
      firstName: "ggg",
      lastName: "ggg",
      email: "ggg@ggg.com",
      password: "$2b$10$Un2WHObrQ1zfJkvKjqdfRuOULtthrQUSrcH23pcCedBpUherxauF6",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer","Buyer"]',
      defaultRole: null,
      createdAt: "0NaN-NaN-NaNTNaN:NaN:NaN.NaN+NaN:NaN",
      updatedAt: "2023-06-15 15:56:45.666348-03",
    },
    sender: {
      id: 5032,
      firstName: "Cheng ",
      lastName: "Yin",
      email: "fullstack.dev1993@gmail.com",
      password: "$2b$10$0aVKk66gy8NiLScrcmV5NuyCpK1HwFfrV2DN/yOgY02RTDEV186R.",
      isActive: false,
      isEmailVerified: true,
      roles: '["Customer", "buyer"]',
      defaultRole: null,
      createdAt: "2023 06 17 08:54:09",
      updatedAt: "2023-06-06",
    },
  },
];

export const fakeSkills = [
  {
    id: 39,
    name: "Marketing",
  },
  {
    id: 40,
    name: "English",
  },
  {
    id: 41,
    name: "Nigerian",
  },
  {
    id: 42,
    name: "Japanese",
  },
  {
    id: 43,
    name: "Chinese",
  },
  {
    id: 44,
    name: "German",
  },
  {
    id: 45,
    name: "Github",
  },
  {
    id: 46,
    name: "CI/CD",
  },
  {
    id: 47,
    name: "UI/UX",
  },
  {
    id: 48,
    name: "Next.js",
  },
  {
    id: 49,
    name: "Nest.js",
  },
  {
    id: 50,
    name: "Nuxt.js",
  },
  {
    id: 51,
    name: "Vuetify",
  },
  {
    id: 52,
    name: "MySQL",
  },
  {
    id: 53,
    name: "Postgre",
  },
  {
    id: 54,
    name: "TypeORM",
  },
  {
    id: 55,
    name: "Full stack development",
  },
  {
    id: 56,
    name: "Firebase",
  },
  {
    id: 1,
    name: "React",
  },
  {
    id: 2,
    name: "HTML",
  },
  {
    id: 3,
    name: "CSS",
  },
  {
    id: 4,
    name: "JavasScript",
  },
  {
    id: 5,
    name: "TypeScript",
  },
  {
    id: 6,
    name: "jQuery",
  },
  {
    id: 7,
    name: "Vue.js",
  },
  {
    id: 8,
    name: "Angular",
  },
  {
    id: 9,
    name: "Angular.js",
  },
  {
    id: 10,
    name: "ASP.net",
  },
  {
    id: 11,
    name: "Go",
  },
  {
    id: 12,
    name: "R",
  },
  {
    id: 13,
    name: "MongoDB",
  },
  {
    id: 14,
    name: "MariaDB",
  },
  {
    id: 15,
    name: "Firebase",
  },
  {
    id: 16,
    name: "Azure",
  },
  {
    id: 17,
    name: "Netlify",
  },
  {
    id: 18,
    name: "Vercel",
  },
  {
    id: 19,
    name: "Git",
  },
  {
    id: 20,
    name: "Jest",
  },
  {
    id: 21,
    name: "Tensorflow",
  },
  {
    id: 22,
    name: "Webflow",
  },
  {
    id: 23,
    name: "PHP",
  },
  {
    id: 24,
    name: "Wordpress",
  },
  {
    id: 25,
    name: "Wordpress theme",
  },
  {
    id: 26,
    name: "Worepress Plugin",
  },
  {
    id: 27,
    name: "Python",
  },
  {
    id: 28,
    name: "Django",
  },
  {
    id: 29,
    name: "Laravel",
  },
  {
    id: 30,
    name: "Codeignitor",
  },
  {
    id: 31,
    name: "Api",
  },
  {
    id: 32,
    name: "API development",
  },
  {
    id: 33,
    name: "Design",
  },
  {
    id: 34,
    name: "Figma",
  },
  {
    id: 35,
    name: "Sketch",
  },
  {
    id: 36,
    name: "Adobe",
  },
  {
    id: 37,
    name: "Photoshop",
  },
  {
    id: 38,
    name: "Scraping",
  },
];
